Lesson 09 metaprogramming
askrynnikov/samurai pull request #6
Opened 2016-11-29 09:50 UTC by askrynnikov

2016-11-29 21:33 UTC, psylone requested changes

2016-11-29 21:33 UTC, psylone commented on railway/lib/accessors.rb
> +      raise TypeError 'method name  is not symbol' unless method.is_a?(Symbol)
Учитывая интерполяцию, строка тоже сработает. Вообще пользователь API должен понимать какие типы данных необходимо использовать, поэтому я бы отказался от этой проверки.

2016-11-29 21:33 UTC, psylone commented on railway/lib/accessors.rb
> +      define_method(method) { instance_eval("@#{method}.last") }
Почему `last`? У меня здесь `instance_eval': undefined method last' for nil:NilClass (NoMethodError)`.

2016-11-29 21:33 UTC, psylone commented on railway/lib/accessors.rb
> +          instance_eval("@#{method} = []")
Немного не понял логику, у меня при вызове обычного аксессора значение заворачивается в массив, так не должно быть:

```ruby
class Human

  extend Accessors

  attr_accessor_with_history :name
  
end

human = Human.new
human.name = 21
human.name # => [21]
```

2016-11-29 21:33 UTC, psylone commented on railway/lib/accessors.rb
> +    raise TypeError 'method name  is not symbol' unless method.is_a?(Symbol)
То же что выше.

2016-11-29 21:33 UTC, psylone commented on railway/lib/accessors.rb
> +  def attr_accessor_with_history(*methods)
Это скорее не `methods`, а `attributes` или `values`.

2016-11-29 21:33 UTC, psylone commented on railway/lib/accessors.rb
> +      raise TypeError "value is not #{type}" unless v.is_a?(type)
Не нужна ли здесь запятая в аргументах `raise`?

2016-11-29 21:33 UTC, psylone commented on railway/lib/route.rb
> +  class NoStation < TypeError
Если это `TypeError`, то лучше `NotStation`.

2016-11-29 21:33 UTC, psylone commented on railway/lib/validation.rb
> +    rescue TypeError
Я бы оставил `StandardError`. Могут же быть у нас валидации общего типа. Кроме того, валидация на проверку существования это с одной стороны ошибка типа данных, а с другой стороны - нет, потому что и данных-то нет, а значит нет и типа.

2016-11-29 21:33 UTC, psylone commented on railway/lib/validation.rb
> +      while context != Object
Это очень грамотно!

2016-11-29 21:33 UTC, psylone commented on railway/lib/validation.rb
> +            checking(variable, check[:type], check[:option])
Через `send` можно избежать этого общего метода и сразу вызывать нужный метод валидации.

2016-11-30 03:51 UTC, askrynnikov commented on railway/lib/accessors.rb
> +          instance_eval("@#{method} = []")
.last отрабатывает и получаем не [21] а 21

2016-11-30 03:58 UTC, askrynnikov commented on railway/lib/accessors.rb
> +      define_method(method) { instance_eval("@#{method}.last") }
допилил `instance_eval("@#{attr}.last") if instance_eval("@#{attr}")`

2016-11-30 21:40 UTC, psylone approved these changes

2016-12-01 06:13 UTC, merged